export const DataDummy = [
    {
        id: 1,
        fname: "Arty",
        lname: "Dunlap",
        email: "adunlap0@yolasite.com",
        moblie: "+57 478 689 0586",
        gender: "Male",
        dob: "2023/10/18",
        address: "Apt 778",
        city: "Momil",
        pin: "11673-141",
        state: null,
        education: "Suzuki",
        hobby: "Yankee"
    },
    {
        id: 2,
        fname: "Dwight",
        lname: "Mackelworth",
        email: "dmackelworth1@shareasale.com",
        moblie: "+354 618 235 8697",
        gender: "Male",
        dob: "2023/05/18",
        address: "Suite 16",
        city: "Akureyri",
        pin: "10596-341",
        state: null,
        education: "Mercury",
        hobby: "Alfa"
    },
    {
        id: 3,
        fname: "Muffin",
        lname: "Neggrini",
        email: "mneggrini2@printfriendly.com",
        moblie: "+63 933 832 1761",
        gender: "Male",
        dob: "2023/05/28",
        address: "Suite 51",
        city: "Capas",
        pin: "51346-116",
        state: null,
        education: "Lamborghini",
        hobby: "Golf"
    },
    {
        id: 4,
        fname: "Sophronia",
        lname: "Dulling",
        email: "sdulling3@dell.com",
        moblie: "+62 827 175 4344",
        gender: "Female",
        dob: "2023/11/17",
        address: "5th Floor",
        city: "Margasari",
        pin: "50114-0227",
        state: null,
        education: "Dodge",
        hobby: "Papa"
    },
    {
        id: 5,
        fname: "Bronny",
        lname: "Eykelbosch",
        email: "beykelbosch4@timesonline.co.uk",
        moblie: "+1 863 570 9151",
        gender: "Male",
        dob: "2023/05/25",
        address: "Apt 773",
        city: "Lakeland",
        pin: "54569-2059",
        state: "Florida",
        education: "Ford",
        hobby: "Zulu"
    },
    {
        id: 6,
        fname: "Charil",
        lname: "Drohan",
        email: "cdrohan5@hexun.com",
        moblie: "+7 437 751 6464",
        gender: "Female",
        dob: "2023/02/01",
        address: "Apt 776",
        city: "Novyye Kuz’minki",
        pin: "36987-2712",
        state: null,
        education: "Volkswagen",
        hobby: "Papa Kilo"
    },
    {
        id: 7,
        fname: "Adi",
        lname: "Keetch",
        email: "akeetch6@tumblr.com",
        moblie: "+55 573 768 2979",
        gender: "Female",
        dob: "2023/08/06",
        address: "Apt 1929",
        city: "Ilhéus",
        pin: "10913-001",
        state: null,
        education: "Saab",
        hobby: "Quebec"
    },
    {
        id: 8,
        fname: "Isador",
        lname: "Alenichev",
        email: "ialenichev7@state.gov",
        moblie: "+63 798 654 5356",
        gender: "Male",
        dob: "2023/06/07",
        address: "PO Box 56525",
        city: "Tungawan",
        pin: "49999-906",
        state: null,
        education: "BMW",
        hobby: "Juliett"
    },
    {
        id: 9,
        fname: "Dale",
        lname: "Bullimore",
        email: "dbullimore8@google.co.jp",
        moblie: "+86 121 621 6956",
        gender: "Male",
        dob: "2023/05/08",
        address: "4th Floor",
        city: "Jiaowei",
        pin: "68788-9101",
        state: null,
        education: "Buick",
        hobby: "Victor"
    },
    {
        id: 10,
        fname: "Siana",
        lname: "Gautrey",
        email: "sgautrey9@linkedin.com",
        moblie: "+254 228 575 4500",
        gender: "Female",
        dob: "2023/12/30",
        address: "Suite 79",
        city: "Maralal",
        pin: "0378-2537",
        state: null,
        education: "Toyota",
        hobby: "Golf"
    }
]